### ISSUE TITLE
안녕하세요

### ISSUE THREAD

**Issue by kose-y** [snu-stat/cs17-commonplace#1]
안녕하세요

**Comment by Provy3** [comment]
조교님 안녕하세요~

**Comment by RyuJeeho** [comment]
@kose-y 
조교님 제가 직접 풀이를 쓴 스캔본pdf 하나와 R Markdown 파일 하나를 push한 뒤에
doc 폴더에 옮기려고 했는데 어떻게 해도 안 옮겨지네요... 처음에 push 할 때 doc 폴더 안에 있었어야 하나요?
그리고 R Markdown 파일을 knit 해서 pdf를 만들려고 했는데 무슨 오류인지 코드는 따로 잘 돌아가는데
 knit가 안돼서 latex를 깔고 있으나, latex를 까는데 자꾸 컴퓨터에 오류가 떠서 R Markdown에 설명까지 다 써서 넣었습니다.ㅠㅠ

**Comment by kose-y** [comment]
@RyuJeeho 

새로운 질문은 새로은 이슈를 만들어서 해 주면 좋겠습니다.

지금 학생은 github에서 무언가를 직접 수정한 상황이니, 
* 일단 pull을 통해 로컬 저장소에 이를 업데이트한 후, 
* 로컬 저장소에서 파일을 원하는 대로 옮긴 뒤에 commit-push하면 이동될 것입니다. 

지금은 남은 시간이 많지 않으니 그렇게 받도록 하겠습니다. 숙제 2부터는 pdf나 html로 만들어 내지 않을 경우 최대 감점(만점의 10%)이 부여될 예정입니다.
