### ISSUE TITLE
[HW2] 7번문제 IRLS SAheart.data를 쓰는 것이 맞나요?

### ISSUE THREAD

**Issue by niffler92** [snu-stat/cs17-commonplace#10]
아래와 같은 오류가 납니다.
`Error in read.table("../data/SAheart.data", header = TRUE) : 열의 개수가 열의 이름들보다 많습니다`

**Comment by kose-y** [comment]
맞습니다. 다른 방법으로 오류 없이 데이터 파일을 읽어들일 수 있습니다.

**Comment by kose-y** [comment]
이 데이터 파일을 R에서 읽는 코드를 여기서 공유해도 좋습니다. (there might be a bonus...)

**Comment by niffler92** [comment]
앗 죄송합니다 제가 sep argument 고려를 안했습니다.
다른 분들 혹시나 참고하실 코드는 아래와 같습니다.
data = read.table('../data/SAheart.data', sep = ",", header=TRUE, row.names = 'row.names')
